import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.GregorianCalendar;
import java.rmi.Naming;
import javax.swing.JOptionPane;

public class TelaNovoFunc extends javax.swing.JFrame {
   
	private static final long serialVersionUID=1L;    

    public TelaNovoFunc() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGround = new javax.swing.JLabel();
        Nome = new javax.swing.JLabel();
        Idade = new javax.swing.JLabel();
        Telefone = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        JtfNome = new javax.swing.JTextField();
        TextfieldEndereco = new javax.swing.JTextField();
        JtfTel = new javax.swing.JTextField();
        JtfEmail = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        TextFieldCPF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldData = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldRG = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();

        BackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/TelaLimpa.png"))); // NOI18N
        BackGround.setToolTipText("");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Novo Usuario");
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(705, 505));
        setResizable(false);
        getContentPane().setLayout(null);

        Nome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Nome.setText("Nome:");
        getContentPane().add(Nome);
        Nome.setBounds(30, 80, 110, 40);

        Idade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Idade.setText("Endereço:");
        getContentPane().add(Idade);
        Idade.setBounds(30, 110, 130, 40);

        Telefone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Telefone.setText("Telefone:");
        getContentPane().add(Telefone);
        Telefone.setBounds(30, 140, 140, 40);

        Email.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Email.setText("Email:");
        getContentPane().add(Email);
        Email.setBounds(30, 210, 140, 40);

        JtfNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JtfNome.setToolTipText("");
        JtfNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JtfNomeKeyPressed(evt);
            }
        });
        getContentPane().add(JtfNome);
        JtfNome.setBounds(160, 90, 240, 20);

        TextfieldEndereco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TextfieldEndereco.setToolTipText("");
        getContentPane().add(TextfieldEndereco);
        TextfieldEndereco.setBounds(160, 120, 240, 20);

        JtfTel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JtfTel.setToolTipText("");
        getContentPane().add(JtfTel);
        JtfTel.setBounds(160, 150, 240, 20);

        JtfEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JtfEmail.setToolTipText("");
        getContentPane().add(JtfEmail);
        JtfEmail.setBounds(160, 220, 240, 20);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setText("Cadastrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 290, 140, 50);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(250, 290, 150, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("CPF:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 20, 90, 40);

        TextFieldCPF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(TextFieldCPF);
        TextFieldCPF.setBounds(160, 30, 240, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Data de Nasc.:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 180, 140, 22);

        jTextFieldData.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(jTextFieldData);
        jTextFieldData.setBounds(160, 180, 240, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("RG:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 50, 100, 40);

        jTextFieldRG.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(jTextFieldRG);
        jTextFieldRG.setBounds(160, 60, 240, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Administrador:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 240, 150, 40);

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(160, 250, 20, 21);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JtfNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtfNomeKeyPressed
        // Evento tecla ESC apertada em cima do primeiro campo nome
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.dispose();
        }
    }//GEN-LAST:event_JtfNomeKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Evento de click no botao salvar
        try{
			if(TextFieldCPF.getText().equals("")||jTextFieldRG.getText().equals("")||JtfNome.getText().equals("")||
				TextfieldEndereco.getText().equals("")||JtfTel.getText().equals("")||jTextFieldData.getText().equals("")||JtfEmail.getText().equals(""))
				throw new RuntimeException("Preencha todos os campos");
			if(TextFieldCPF.getText().length()<10||TextFieldCPF.getText().length()>13)
				throw new RuntimeException("O CPF deve conter apenas numeros e entre 10 e 13 numeros");
			if(jTextFieldRG.getText().length()<8||jTextFieldRG.getText().length()>12)
   				throw new RuntimeException("O RG deve conter apenas numeros e entre 8 e 12 numeros");
			String email = JtfEmail.getText();
            if(email.equals("")) email="0";
            
	        SimpleDateFormat sdf=new SimpleDateFormat("dd/MM/yyyy");
			sdf.setLenient(false);
			Calendar cal=Calendar.getInstance();
			Date date1=sdf.parse(jTextFieldData.getText());
			cal.setTime(date1);
			String Data=cal.get(Calendar.YEAR)+"-"+cal.get(Calendar.MONTH)+"-"+cal.get(Calendar.DATE);
            
         	long chavecpf=Long.valueOf(TextFieldCPF.getText());
            int rg=Integer.valueOf(jTextFieldRG.getText());
			int fone=Integer.valueOf(JtfTel.getText());
			boolean admin=jCheckBox1.isSelected();

			Funcionario f=new Funcionario(chavecpf, rg, JtfNome.getText(), TextfieldEndereco.getText(),
					fone, Data, JtfEmail.getText(), admin);
			Requisicao req=new Requisicao();
			req.setTipo(Requisicao.CadastroFuncionario);
			req.setFuncionario(f);
			Server_Interface server=(Server_Interface)Naming.lookup("rmi://localhost/Servidor");
			Resposta rep=server.CadastraFuncionario(req);
			int tipo=rep.getTipo();

			if(tipo==Resposta.ErroCPF)
				throw new RuntimeException("CPF ja existente no banco de dados");
			else if(tipo==Resposta.CadastroFuncionario)
            	JOptionPane.showMessageDialog(this, "Cadastro Efetuado com Sucesso");
			else if(tipo==Resposta.ErroCadastroFuncionario)
				throw new RuntimeException("Cadastro nao efetuado.");
			else
				throw new RuntimeException("Cadastro nao efetuado.\nErro Desconhecido");

            this.dispose();
        }catch(NumberFormatException e){
             JOptionPane.showMessageDialog(this, "Digite o RG, CPF e/ou Telefone apenas com numeros");
        }catch(RuntimeException e){
			JOptionPane.showMessageDialog(this, ""+e.getMessage());
		}catch(Exception e){
			JOptionPane.showMessageDialog(this, "Falha na Conexão com o Servidor");
		}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Botao cancelar Clickado
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaNovoFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaNovoFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaNovoFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaNovoFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaNovoFunc().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGround;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Idade;
    private javax.swing.JTextField JtfEmail;
    private javax.swing.JTextField JtfNome;
    private javax.swing.JTextField JtfTel;
    private javax.swing.JLabel Nome;
    private javax.swing.JLabel Telefone;
    private javax.swing.JTextField TextFieldCPF;
    private javax.swing.JTextField TextfieldEndereco;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextFieldData;
    private javax.swing.JTextField jTextFieldRG;
    // End of variables declaration//GEN-END:variables

}
